milkshakesoftware/PreMailer.Net

PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/CssParser.cs, PreMailer.Net/PreMailer.Net/CssSelector.cs, PreMailer.Net/PreMailer.Net/CssSelectorParser.cs, PreMailer.Net/PreMailer.Net/PreMailer.cs
We are using PreMailer to inline our CSS, but also need to add Analytics tags. It is a lot more overhead per email to re-parse the entire HTML all over again with another instance of CsQuery to do the analytics tags processing, so it works faster if we moved our code for this into PreMailer. Plus I hope someone else will find this useful.
=> Add analytics tags using PreMailer

PreMailer.Net/PreMailer.Net/CssParser.cs, PreMailer.Net/PreMailer.Net/CssSelector.cs, PreMailer.Net/PreMailer.Net/CssSelectorParser.cs
Originally when I started fixing the static regex code to be compiled, performance was terrible. So I took it all out and made sure none of the regex'es were compiled. However going back and doing performance profiling on some other regex'es we use I discovered that compiled regex'es are in fact faster, when you need to use them over and over. There is a performance hit the first time a regex is used as it is compiled, but every time after that it is always faster than the non-compiled ones.
Since PreMailer is really intended to be used for batch processing of emails or in code that is going to re-use the static regex'es over and over again (like a web site sending emails in response to customer input), it makes sense to have them all compiled. 
The core reason the performance as so …
=> Compiled Regexes for speed

PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/CssElementStyleResolver.cs, PreMailer.Net/PreMailer.Net/StyleClassApplier.cs
For example:
table { -premailer-cellspacing: 5; -premailer-width: 500; }
will result in
<table cellspacing="5" width="500">
Reference: https://github.com/premailer/premailer
=> Added support for premailer-specific CSS

PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/PreMailer.cs
I found a way to run all the Pre-Mailer stuff prior to rendering our Handlebars templates, but that means we need to remove the analytics tracking tags from URL generated by the template (we assume the caller decorates the URL's correctly).
=> Do not add Analytics tracking tags when using Handlebars syntax

PreMailer.Net/PreMailer.Net.Tests/CssParserTests.cs, PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/CssParser.cs, PreMailer.Net/PreMailer.Net/PreMailer.cs, PreMailer.Net/PreMailer.Net/StyleClass.cs
This is to take into account "where" (relatively speaking) a selector is
found when parsing a css body. Then, this is taken into account during
SortBySpecificity, so if the Specificity score is the same, its position
is then the deciding factor.
This could also fix #53 although I've not tested that.
=> Add Position property to StyleClass class.

PreMailer.Net/PreMailer.Net.Tests/PreMailer.Net.Tests.csproj, PreMailer.Net/PreMailer.Net.Tests/packages.config, PreMailer.Net/PreMailer.Net/PreMailer.Net.csproj, PreMailer.Net/PreMailer.Net/packages.config
Hey great library but I was having some inconsistent behavior as i was using 0.9.5 of AngleSharp in my project.
All the tests pass and i've made no changes but bumping the version,
Cheers
=> Bump AngleSharp to version 0.9.5

PreMailer.Net/PreMailer.Net.Tests/LinkTagCssSourceTests.cs, PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/PreMailer.cs
Hello!
I noticed that in last update:
> PreMailer will download and use external style sheets as long as the value of href ends with .css.
It is great feature!
But unfortunately, ASP.NET (MVC) bundle ends with query, and not contains ".css" at all.
Can you extend CssLinkNodes method to return rel="stylesheet" also?
```
return elements.Where(e => e.Attributes
.Any(a => a.Name.Equals("href", StringComparison.OrdinalIgnoreCase) &&
(a.Value.EndsWith(".css", StringComparison.OrdinalIgnoreCase) || 
(e.Attributes.Any(r => r.Name.Equals("rel", StringComparison.OrdinalIgnoreCase) &&
r.Value.Equals("stylesheet", StringComparison.OrdinalIgnoreCase))))));
```
=> #67: Download bundle link <link href="..." rel="stylesheet">

PreMailer.Net/PreMailer.Net.Tests/LinkTagCssSourceTests.cs, PreMailer.Net/PreMailer.Net/Sources/LinkTagCssSource.cs
We have recently begun using Premailer in a high traffic environment (and we love it). We've run into a handful of users who have inadvertently injected client-side CSS links, and currently Premailer throws an exception when it tries to inline it. That's because underneath, it uses WebClient, which only supports four URI schemes.
Here's a suggested fix which only attempts to download from the four supported schemes, including a supporting test. Would love any feedback! Thanks.
=> Fix for occasional crash due to unsupported URI schemes

PreMailer.Net-dotnet/PreMailer.Net.csproj, PreMailer.Net-dotnet/PreMailer.Net.nuspec, PreMailer.Net-dotnet/nuget.bat, PreMailer.Net/PreMailer.Net/Downloaders/WebDownloader.cs, PreMailer.Net/PreMailer.Net/Sources/LinkTagCssSource.cs
I propose this merge request to support .NET Core with RC4 tooling.
Compared to pull request #122, the suggested modifications are very minor:
- Only five lines had to be changed in the source code in order to comply with .NET Core APIs. These changes are retrocompatible with standard .NET Framework.
- The dotnet core publish process is in a new directory `PreMailer.Net-dotnet`.
Install [.NET Core SDK 1.0 rc4](https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md), execute `nuget.bat` inside `PreMailer.Net-dotnet`, and that should be it.
I stay available if you need any help.
=> Make the project compatible with .NET Core RC4

.gitignore, PreMailer.Net/.gitignore, PreMailer.Net/PreMailer.Net/PreMailer.Net.csproj
PreMailer is a perfect complement for [MailMergeLib](https://github.com/axuno/MailMergeLib), which supports .Net Core and .Net Framework 4.5+. Currently the nuget package only includes .Net Core support, so we'd be more than happy if .Net Framework could be added, as it works perfectly here as well.
=> Support for .NET Framework 4.5 and up, besides .NET Core 2

PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/CssParser.cs
- When received e-mail from Microsoft Outlook on Desktop, the e-mail comes with style tag having an HTML comment Block in.
- On browsers, this comment will be ignored and CSS was processed.
- When processed by PreMailer, the first CSS will be ignored because it will be merged with comment text.
- Remove the HTML block comment chars of CSS styles.
=> [BUG] Problem when Style tag contain html comment tags

PreMailer.Net/.editorconfig, PreMailer.Net/PreMailer.Net/PreMailer.cs
Added extra constructor that takes an existing HtmlDocument. This allows for scenarios where the document has already been parsed (ie, run through an Html Sanitizer first).
=> Additional PreMailer constructor

PreMailer.Net/PreMailer.Net/PreMailer.cs, PreMailer.Net/PreMailer.Net/Sources/LinkTagCssSource.cs
Catch webexception and add to InlineResult warnings
=> Handle bad external css links

PreMailer.Net/PreMailer.Net/Downloaders/WebDownloader.cs
Add support on fetching Uri with local filepath like "file:///C:/website/style.css"
It's required when we optimize the performance by fetching the local resource internally instead of making external web request towards internal resource.
e.g. As I know the css is actually inside the local storage, it make sense to just make a fast local fetch ("file:///C:/website/style.css") instead of external web request ("https://www.mysite.com/style.css")
So I can now initialize a PreMailer instance with BaseUri `"file:///" + new Uri(System.Web.Hosting.HostingEnvironment.MapPath("~/"), UriKind.Absolute)`
It's how I boost the performance for my client, just share my code here.
=> Add support on fetching Uri with local filepath

PreMailer.Net/PreMailer.Net/PreMailer.cs
All I've done in this change is add an optional parameter for a custom IMarkupFormatter that can be supplied to PreMailer.Net for special circumstances where the provided MarkupFormatters are not working for the client's needs.
The issue was caused by the default behavior used in AngleSharp, which provides an interface for custom formatters in case that behavior does not work. This change simply exposes that interface as an option in PreMailer.Net and passes it onto AngleSharp.
I implemented this specifically to address the problem I was having in this issue:
https://github.com/milkshakesoftware/PreMailer.Net/issues/193
I also collaborated with @FlorianRappl - the primary author of AngleSharp to reach this implementation. Please let me know if you have any questions or concerns about this …
=> Add optional custom markupformatter parameter

PreMailer.Net/PreMailer.Net.Tests/CssParserTests.cs, PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/CssAttributeCollection.cs, PreMailer.Net/PreMailer.Net/CssParser.cs, PreMailer.Net/PreMailer.Net/StyleClass.cs
This fixes the newfound [problem case](https://github.com/milkshakesoftware/PreMailer.Net/issues/53#issuecomment-826581429) of #53.
This pull request will:
- Introduce a new public class `CssAttributeCollection`.
- Changes a Public API `StyleClass.Attributes { get; set; }` form `Dictionary<string, CssAttribute>` to `CssAttributeCollection` while CssAttributeCollection inherits from `IDictionary<string, CssAttribute>`, so there should be only a minimal breaking change.
Side effect of this change:
- Since this will keep the local order of css attributes it may also change the order of nonrelated style attributes, like: `line-height` and `font-size` as seen in `PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs`
=> Fix: Keep css attributes in logical order (#53)

PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/PreMailer.cs
As per https://tools.ietf.org/html/rfc3986#section-4.1 anchor tags (#) should be appended after query string params.
Issue #254
=> Append analytics query string before anchor tag

PreMailer.Net/PreMailer.Net.Tests/CssAttributeTests.cs, PreMailer.Net/PreMailer.Net.Tests/StyleClassApplierTests.cs, PreMailer.Net/PreMailer.Net.Tests/StyleClassTests.cs, PreMailer.Net/PreMailer.Net/CssAttribute.cs, PreMailer.Net/PreMailer.Net/CssElementStyleResolver.cs, PreMailer.Net/PreMailer.Net/StyleClass.cs
This pull request removes `!important` from generated inline styles.
This change makes sense because the intention of `!important` is to overwrite inline styles,
so inline styles with `!important` have no real reason to exist.
And as seen in #149 Outlook considers inline styles with it as invalid and ignores them as a whole.
I thought about making this change configurable, but I don't see a benefit from doing so.
I hope this pull request is welcome.
Best regards
=> Fix: Generate inline styles without !important (#149)

PreMailer.Net/PreMailer.Net.Tests/CssParserTests.cs, PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs
This fixes build warnings like:
```
> warning xUnit2009: Do not use Assert.False() to check for substrings.
> warning xUnit2009: Do not use Assert.True() to check for substrings.
> warning xUnit2009: Do not use Assert.....
```
=> Fix: Build warning xUnit2009: Do not use ..

PreMailer.Net/PreMailer.Net.Tests/PreMailerTests.cs, PreMailer.Net/PreMailer.Net/CssParser.cs, PreMailer.Net/PreMailer.Net/PreMailer.cs
Currently, if using `removeStyleElements` while also having media queries in `<style>` in `<head>` which cannot be inlined, these media queries will be lost.
This adds a new parameter `preserveMediaQueries` which instead of removing the entire `<style>` node, will replace the inner styles with just the unsupported media queries
I realise you already have a a workaround for this of setting an id on the style node and using `ignoreElements` so feel free to close this if you would prefer to keep it as is
=> Preserve unsupported media queries in head element

PreMailer.Net/Benchmarks/Benchmarks.csproj, PreMailer.Net/Benchmarks/Program.cs, PreMailer.Net/PreMailer.Net.sln
Runs a benchmark on a decently sized email HTML through both a baseline bench called `AngleSharpBaseline` and a realistic no-options `MoveCssInline`.
|             Method |     Mean |   Error |   StdDev |   Median |    Gen0 | Allocated |
|------------------- |---------:|--------:|---------:|---------:|--------:|----------:|
| AngleSharpBaseline | 170.6 us | 6.79 us | 20.03 us | 164.9 us |       - | 138.67 KB |
|      MoveCssInline | 832.4 us | 5.43 us | 14.69 us | 830.9 us | 30.0000 | 621.52 KB |
=> Realistic benchmark

PreMailer.Net/Benchmarks/Program.cs
It looks a bit different from the default one because it triggers various features.
There is no special magic with the strings, it's just intended to properly trigger the corresponding feature.
|                 Method |     Mean |   Error |   StdDev |   Median |    Gen0 | Allocated |
|----------------------- |---------:|--------:|---------:|---------:|--------:|----------:|
|     AngleSharpBaseline | 170.2 us | 6.44 us | 19.00 us | 162.8 us |       - | 138.43 KB |
|          MoveCssInline | 826.6 us | 4.63 us | 12.44 us | 825.3 us | 30.0000 | 621.16 KB |
| MoveCssInline_AllFlags | 895.0 us | 5.60 us | 15.90 us | 892.0 us | 30.0000 | 634.99 KB |
=> Include a benchmark that sets all MoveCssInline() flags

PreMailer.Net/PreMailer.Net.Tests/CssParserTests.cs, PreMailer.Net/PreMailer.Net/CssAttributeCollection.cs, PreMailer.Net/PreMailer.Net/CssElementStyleResolver.cs, PreMailer.Net/PreMailer.Net/StyleClass.cs
The core change is that we don't try to be a dictionary anymore, just a simple list. No need for the `CssValue` struct either, just store the `CssAttribute` directly in the list. The order of the list is the same as the attribute order, so no need to sort it every time we want to iterate over it.
Because this is a public type, these are probably considered breaking changes.
One invocation of MoveCssInline()
Original: 1.2ms 592kB
After:  1.0ms 482kB
=> Decent optimizations for CssAttributeCollection

PreMailer.Net/PreMailer.Net.Tests/Extensions/NodeExtensionTests.cs, PreMailer.Net/PreMailer.Net/Extensions/NodeExtensions.cs, PreMailer.Net/PreMailer.Net/PreMailer.Net.csproj, PreMailer.Net/PreMailer.Net/PreMailer.cs, PreMailer.Net/PreMailer.Net/Sources/DocumentStyleTagCssSource.cs
Because reading `InnerHtml` causes serialization to HTML, with some overhead. Reading the raw data from the text node has no overhead.
A small but easy win for allocations.
|                 Method |     Mean |   Error |   StdDev |   Median |    Gen0 | Allocated |
|----------------------- |---------:|--------:|---------:|---------:|--------:|----------:|
|     AngleSharpBaseline | 170.2 us | 6.44 us | 19.00 us | 162.8 us |       - | 138.43 KB |
|          MoveCssInline | 826.6 us | 4.63 us | 12.44 us | 825.3 us | 30.0000 | 621.16 KB |
| MoveCssInline_AllFlags | 895.0 us | 5.60 us | 15.90 us | 892.0 us | 30.0000 | 634.99 KB |
|                 Method |     Mean |   Error |   StdDev |   Median |    Gen0 | Allocated |
|----------------------- …
=> Read text node instead of InnerHtml for CSS

PreMailer.Net/PreMailer.Net/PreMailer.cs
Goes through the entire tree just once, and with selectors already parsed.
Basically the same that already happened when `QuerySelectorAll(selector)` was called, but we do it element by element ourselves.
Selector parsing could be done earlier and possibly be part of `StyleClass`. An `ISelector` also provides a specificity calculation, which could possibly replace the custom calculator built for PreMailer and save us further resources. I will create an issue.
|                 Method |     Mean |   Error |   StdDev |   Median |    Gen0 | Allocated |
|----------------------- |---------:|--------:|---------:|---------:|--------:|----------:|
|     AngleSharpBaseline | 170.2 us | 6.44 us | 19.00 us | 162.8 us |       - | 138.43 KB |
|          MoveCssInline | 826.6 us | 4.63 us | 12.44 us | …
=> More efficient selector matching of all elements

PreMailer.Net/PreMailer.Net.Tests/PreMailer.Net.Tests.csproj
netcoreapp was [replaced](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks) with net since v5.
=> use correct framework

PreMailer.Net/PreMailer.Net.Tests/AssemblyInfo.cs
xUnit by default will parallelize tests between tests collections (classes). The WebDownloader.SharedDownloader property was being set between multiple collections causing a race condition on which SharedDownloader object was used. This caused the first test to fail because it ran a validation against another mock object for another test.
=> Fix race condition when running unit tests

PreMailer.Net/PreMailer.Net/PreMailer.Net.csproj
* Bump AngleSharp from 0.16.1 to 1.0.7. Only the IMarkupFormatter from AngleSharp is exposed as public api and that interface has not changed in that version jump so this should not cause any breakages for users.
* Dependency Bumps for the Tests and Benchmark projects.
* Fix race condition when running unit tests by @jasekiw in https://github.com/milkshakesoftware/PreMailer.Net/pull/374
* Normalize all file line endings by @jasekiw in https://github.com/milkshakesoftware/PreMailer.Net/pull/365
* Update benchmark project framework by @jasekiw in https://github.com/milkshakesoftware/PreMailer.Net/pull/351
* Use correct framework by @kasperk81 https://github.com/milkshakesoftware/PreMailer.Net/pull/334
* Update CI triggers to main branch  by @martinnormark …
=> Add nuget release details for v2.5.0

PreMailer.Net/PreMailer.Net/PreMailer.Net.csproj
Related to #396
Updates the AngleSharp package version to 1.1.0 in `PreMailer.Net/PreMailer.Net/PreMailer.Net.csproj`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/milkshakesoftware/PreMailer.Net/issues/396?shareId=c046af8f-ce6b-4193-86c6-6f8592865062).
=> Update AngleSharp version to 1.1.0

PreMailer.Net/Benchmarks/Benchmarks.csproj, PreMailer.Net/PreMailer.Net.Tests/PreMailer.Net.Tests.csproj
This pull request includes updates to the target framework and package references for the `PreMailer.Net` project. This will address the failing tests.
The most important changes are as follows:
Framework updates:
* Updated the target framework from `net7.0` to `net9.0` in `PreMailer.Net/Benchmarks/Benchmarks.csproj`.
* Updated the target framework from `net7.0` to `net9.0` in `PreMailer.Net/PreMailer.Net.Tests/PreMailer.Net.Tests.csproj`.
Package reference updates:
* Updated `BenchmarkDotNet` from version `0.13.3` to `0.14.0` in `PreMailer.Net/Benchmarks/Benchmarks.csproj`.
* Updated several package references in `PreMailer.Net/PreMailer.Net.Tests/PreMailer.Net.Tests.csproj`:
* `Microsoft.NET.Test.Sdk` from version `17.9.0` to `17.12.0`
* `Moq` from version `4.20.70` to `4.20.72`
* …
=> Update target frameworks of test and benchmark projects
